apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.persistence.dbPassword }}
  PASSWORD: {{ .Values.persistence.dbPassword | quote }}
  {{- end }}