apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.persistence.dbName | default .Release.Namespace }}
  POSTGRES_USER: {{ .Values.persistence.dbUser | default .Release.Namespace}}