apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: postgresql
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}

# spec:
#   type: NodePort
#   # type: ClusterIP
#   ports:
#     - name: postgresql
#       port: 3306
#       protocol: TCP
#       # targetPort: 3306
#       # nodePort: 30001
#   selector:
#     app.kubernetes.io/name: postgresql
# status:
#   loadBalancer: {}
