apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
data:
    PGADMIN_DEFAULT_EMAIL: "{{ .Values.pgadmin.adminEmail }}"
    PGADMIN_PORT: "{{ .Values.service.port }}"
