apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.persistence.name }}
  USER: {{ .Values.persistence.user }}
  HOST: {{ .Values.persistence.dbHost }}