apiVersion: v1
kind: Secret
metadata:
  name: {{ include "phpmyadmin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.phpmyadmin.rootPassword | b64enc }}
