apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpmyadmin.fullname" . }}2
  labels:
    {{- include "phpmyadmin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service2.type }}
  ports:
    - port: {{ .Values.service2.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service2.nodePort }}
      nodePort: {{ .Values.service2.nodePort }}
      {{- end }}
  selector:
    {{- include "phpmyadmin.selectorLabels" . | nindent 4 }}
