apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.database.dbName }}
  MYSQL_USER: {{ .Values.database.dbUser }}
