apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  #MYSQL_DATABASE
  MARIADB_DATABASE: {{ .Values.database.dbName }}
  MARIADB_MYSQL_LOCALHOST_USER: "{{ .Values.database.localDbUser }}"
  MARIADB_MYSQL_LOCALHOST_GRANTS: "RELOAD, PROCESS, LOCK TABLES, BINLOG MONITOR"
  # MYSQL_USER
  MARIADB_USER: {{ .Values.database.dbUser }}
