apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitea.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
data:
  GITEA__database__DB_TYPE: postgres
  GITEA__database__HOST: db:5432
  GITEA__database__NAME: gitea
  GITEA__database__USER: gitea
  POSTGRES_DB: {{ .Values.database.name }}
  USER: {{ .Values.database.user }}
  HOST: {{ .Values.database.host }}