apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glpi.fullname" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "glpi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "glpi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "glpi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: config
          image: "{{ .Values.image.initRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
          command: ['/opt/glpi/glpi-install.sh']
          envFrom:
            - configMapRef:
                name: {{ include "glpi.fullname" . }}
            - secretRef:
                name: {{ include "glpi.fullname" . }}
          volumeMounts:
            - name: {{ include "glpi.fullname" . }}-config
              mountPath: {{ .Values.persistence.mountPaths.config }}
            - name: {{ include "glpi.fullname" . }}-files
              mountPath: {{ .Values.persistence.mountPaths.files }}
            - name: {{ include "glpi.fullname" . }}-marketplace
              mountPath: {{ .Values.persistence.mountPaths.marketplace }}
            - name: {{ include "glpi.fullname" . }}-log
              mountPath: {{ .Values.persistence.mountPaths.log }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "glpi.fullname" . }}
            - secretRef:
                name: {{ include "glpi.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
            # - name: ssh
            #   containerPort: 22
            #   protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
          volumeMounts:
            - name: {{ include "glpi.fullname" . }}-config
              mountPath: {{ .Values.persistence.mountPaths.config }}
            - name: {{ include "glpi.fullname" . }}-files
              mountPath: {{ .Values.persistence.mountPaths.files }}
            - name: {{ include "glpi.fullname" . }}-marketplace
              mountPath: {{ .Values.persistence.mountPaths.marketplace }}
            - name: {{ include "glpi.fullname" . }}-log
              mountPath: {{ .Values.persistence.mountPaths.log }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "glpi.fullname" . }}-files
          persistentVolumeClaim:
            claimName: {{ include "glpi.fullname" . }}-files
        - name: {{ include "glpi.fullname" . }}-log
          persistentVolumeClaim:
            claimName: {{ include "glpi.fullname" . }}-log
        - name: {{ include "glpi.fullname" . }}-config
          persistentVolumeClaim:
            claimName: {{ include "glpi.fullname" . }}-config
        - name: {{ include "glpi.fullname" . }}-marketplace
          persistentVolumeClaim:
            claimName: {{ include "glpi.fullname" . }}-marketplace
