apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glpi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_PASSWORD: {{ .Values.persistence.dbPassword | b64enc }}
  GLPI_DB_USER_PASSWORD: {{ .Values.persistence.dbPassword | b64enc }}