apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glpi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_PASSWORD: {{ .Values.persistence.dbPassword | b64enc }}
  GLPI_DB_USER_PASSWORD: {{ .Values.persistence.dbPassword | b64enc }}
  # glpycrypt.key tar.gz file on base64 encoding. Check the glpi-container 
  {{- if and (.Values.application) (.Values.application.glpicrypt) }}
  GLPI_CRYPT: {{ .Values.application.glpicrypt | b64enc }}
  {{- end }}
