apiVersion: v1
kind: Service
metadata:
  name: {{ include "glpi.fullname" . }}
  labels:
    {{- include "glpi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and ( eq "NodePort" .Values.service.type ) ( .Values.service.nodePort ) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "glpi.selectorLabels" . | nindent 4 }}
