apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.persistence.dbPassword }}
  GITEA__database__PASSWD: {{ .Values.persistence.dbPassword | quote }}
  {{- end }}